name: Linux

on:
  pull_request: null
  workflow_dispatch:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
  push:
    branches:
      - master
  release:
    types:
      - published

env:
  DEPS_VERSION: r1

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        architecture:
          - x86
          - x86_64
    steps:
      - name: Inject Short Variables
        uses: rlespinasse/github-slug-action@v4

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: '${{inputs.myCommit}}'

      - name: Install Dependencies
        run: |
          sudo apt-get install -y yasm
          sudo apt-get install -y ninja-build
          
          if [[ "${{matrix.architecture}}" = "x86" ]]; then
              sudo dpkg --add-architecture i386
              sudo apt-get update
              sudo apt-get install -y gcc-multilib g++-multilib
          fi

      - name: Variables
        run: |
          echo "ZIP_NAME=linux_${{matrix.configuration}}_${{matrix.architecture}}.zip" >> $GITHUB_ENV

      - name: Build
        run: |
          ./scripts/build_all.sh -j4 linux ${{matrix.architecture}} ${{matrix.configuration}} repos "${{env.ZIP_NAME}}"

      - name: Print Info
        if: always()
        run: |
          ./scripts/print_info.sh

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: 'deps_${{env.DEPS_VERSION}}_${{env.GITHUB_REF_NAME_SLUG}}'
          files: '${{env.ZIP_NAME}}'
