name: MacOS

on:
  pull_request: null
  workflow_dispatch:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
  push:
    branches:
      - master
  release:
    types:
      - published

env:
  DEPS_VERSION: r1

jobs:
  build_macos:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        architecture:
          - x86_64
          - arm64
    steps:
      - name: Inject Short Variables
        uses: rlespinasse/github-slug-action@v4

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: '${{inputs.myCommit}}'

      - name: Install Dependencies
        run: |
          brew install yasm
          brew install ninja

      - name: Variables
        run: |
          echo "ZIP_NAME=darwin_${{matrix.configuration}}_${{matrix.architecture}}.zip" >> $GITHUB_ENV

      - name: Build
        run: |
          ./scripts/build_all.sh -j4 darwin ${{matrix.architecture}} ${{matrix.configuration}} repos "${{env.ZIP_NAME}}"

      - name: Print Info
        if: always()
        run: |
          ./scripts/print_info.sh

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: 'deps_${{env.DEPS_VERSION}}_${{env.GITHUB_REF_NAME_SLUG}}'
          files: '${{env.ZIP_NAME}}'
