name: Build Release
'on':
  schedule:
    - cron: 16 11 * * *
  workflow_dispatch:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
  push:
    tags:
      - '*'
env:
  TAG_NAME: nightly
jobs:
  build_windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        architecture:
          - x86
          - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: '${{ inputs.myCommit }}'
      - name: Setup environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: '${{ matrix.architecture }}'
      #build openal-soft
      - name: Configure
        working-directory: repos\openal-soft
        run: >
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.configuration
          }} -DCMAKE_INSTALL_PREFIX:PATH=openal -DLIBTYPE=STATIC
      - name: Build
        working-directory: repos\openal-soft\build
        shell: cmd
        run: |
          ninja
          ninja install
      #build sdl
      - name: Configure
        working-directory: repos\SDL
        run: >
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.configuration
          }} -DCMAKE_INSTALL_PREFIX=sdl -DSDL_STATIC=On -DSDL_SHARED=Off
      - name: Build
        working-directory: repos\SDL\build
        shell: cmd
        run: |
          ninja
          ninja install
      #build zlib
      - name: Configure
        working-directory: repos\zlib
        run: >
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.configuration
          }} -DCMAKE_INSTALL_PREFIX=zlib 
      - name: Build
        working-directory: repos\zlib\build
        shell: cmd
        run: |
          ninja
          ninja install          
      #build release
      - name: Prepare artifact
        shell: pwsh
        run: >
          mkdir dist
          
          xcopy repos\openal-soft\build\openal dist\openal /E/H/C/I
          
          xcopy repos\SDL\sdl dist\sdl /E/H/C/I
          
          xcopy repos\zlib\zlib dist\zlib /E/H/C/I
      - name: Zip Folder For Release
        run: >-
          Compress-Archive -Path dist -DestinationPath ./Windows_${{
          env.TAG_NAME }}_${{ matrix.configuration }}_${{ matrix.architecture
          }}.zip
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: '${{ env.TAG_NAME }}'
          files: >-
            ${{ runner.os }}_${{ env.TAG_NAME }}_${{ matrix.configuration }}_${{
            matrix.architecture }}.zip
